let questions = [];


function AddQuestion(question){
    this.question=question;
    questions.push(this)
}

//btn.onclick=()=>{
 //   const randomIndex=Math.floor(Math.random()*activities.length);
   // const choose=activities[randomIndex];
//
  //  activitybox.textContent=choose.name;
    //describebox.textContent=choose.description;
//}



new AddQuestion("?");
new AddQuestion("What is your favorite childhood memory?")
new AddQuestion("What is the name of your favorite pet as a child?");
new AddQuestion("What is your favorite color?");
new AddQuestion("Where would you like to visit one day?");
new AddQuestion("What is the coolest video you've seen in a while?");
new AddQuestion("What is your corniest joke?");
new AddQuestion("What is your funniest pick up line?");
new AddQuestion("What do you find the most attractive about me physically?");
new AddQuestion("As a person, what do you find the most attractive about me?");
new AddQuestion("What is the coolest thing that happened to you recently?");
new AddQuestion("What is something you're excited about right now?");
new AddQuestion("What do you think is the world's biggest problem?");
new AddQuestion("If money was no problem, what would you do in the next 24 hours?");
new AddQuestion("If you could have just one day with a deceased family member, who would it be?");
new AddQuestion("What is the happiest memory you have with me?");
new AddQuestion("What is something that I do that you really like and want to see more of?");
new AddQuestion("Is there anything I've done in our relationship that you really miss?");
new AddQuestion("What is something I do that maybe you'd like to see less of?");
new AddQuestion("How do you feel I could improve as a partner?");
new AddQuestion("When is the moment you knew I was the one for you?");
new AddQuestion("If you could right now, kiss or hug?");
new AddQuestion("What tv show made you excited when you were little?");
new AddQuestion("What is something that you're worried about right now?");
new AddQuestion("What is something that makes you smile when you think of me?");
new AddQuestion("What is your favorite nickname that I have for you?");
new AddQuestion("When do you miss me the most?");
new AddQuestion("What's the first thing you'll do when you see me in person?");
new AddQuestion("If you had any superpower, what would it be?");
new AddQuestion("What is your dreamcar, the one you would have if money was no object?");
new AddQuestion("What is a core memory of us that sticks out to you?");
new AddQuestion("Is there something I've done in our relationship that really makes you smile?");
new AddQuestion("Is there something that you would like me to work on about myself?");
new AddQuestion("Are you nervous about meeting my family one day?");
new AddQuestion("What would you do if you were here right now?");
new AddQuestion("What is something about me you find really attractive?");
new AddQuestion("Can you name something about me that you admire?");
new AddQuestion("What is one of the things I've written that make you smile the most?");
new AddQuestion("How do you feel when you get an unexpected phone call?");
new AddQuestion("Is there something I do that ever makes you feel anxious?");
new AddQuestion("Is there something I've done that makes you feel uncomfortable?");
new AddQuestion("For the most part, do you feel safe with me?");
new AddQuestion("How do you think your family would react to meeting me for the first time?");
new AddQuestion("How does our taste in music vary from each other?");
new AddQuestion("What is the coolest thing about me?");
new AddQuestion("If you could change anything about yourself what would it be?");
new AddQuestion("What clothes I wear make you want to see more?");
new AddQuestion("What kinds of things make you feel less secure in our relationship?");
new AddQuestion("What can I do to make you feel more secure in our relationship?");
new AddQuestion("How do you feel when you miss me?");
new AddQuestion("How do you handle awkward situations in conversations?");
new AddQuestion("What is the most beautiful thing about being with me?");
new AddQuestion("What do you look forward to the most when we meet in person?");
new AddQuestion("What is something that happened lately that makes you happy?");
new AddQuestion("When you lay down to rest at night, do you dream of me?");
new AddQuestion("What is the funniest thing about your favorite pet?");
new AddQuestion("What is your favorite planet in the Solar System?");
new AddQuestion("What is your favorite number?");
new AddQuestion("What is something I used to do that you really miss?");
new AddQuestion("If you could make one change in the world, what would it be?");
new AddQuestion("How do you feel about the way that you look?");
new AddQuestion("If you could change something about yourself physically what would it be?");
new AddQuestion("If you could change something about your life, what would it be?");
new AddQuestion("What makes you swoon about me?");
new AddQuestion("What is something about who I am that makes you feel blessed to be with me?");

new AddQuestion("What do you feel you've sacrificed the most being in this relationship?");
new AddQuestion("What do you know now that you wish you knew in the beginning of our relationship?");
new AddQuestion("Is there anything you miss about you and me?");
new AddQuestion("If I were on my deathbed what do you think my dying wishes would be?");
new AddQuestion("About our future, what do you think excites me the most?");
new AddQuestion("In our relationship, what do you think excites me the most?");
new AddQuestion("The purpose of life is to ____?");
new AddQuestion("I love you the most when_____?");
new AddQuestion("I get turned on most when you _____?");
new AddQuestion("What has been our greatest accomplishment as a couple in your opinion?");
new AddQuestion("What do you think I'm hesitant to talk to you about?");
new AddQuestion("What do you think I appreciate the most in life right now?");
new AddQuestion("When we're apart, what do you think I miss the most about you?");
new AddQuestion("What do you think I need and are you providing it in your opinion?");
new AddQuestion("What are some things that you would like to understand more about me?");
new AddQuestion("In our relationship, what do you think I value the most now?");
new AddQuestion("If I could hear anything right now, what do you think I'd like to hear the most?");
new AddQuestion("When do you think I'm most worried for you?");
new AddQuestion("What part of our relationship do we take for granted and why do you think that is?");
new AddQuestion("What do you think is our greatest creation together?");
new AddQuestion("How do you feel our relationship has changed over time?");
new AddQuestion("How have I changed in our relationship?");
new AddQuestion("How do you think my habits have changed in our relationship?");
new AddQuestion("Describe your feelings when you're around me");
new AddQuestion("Describe our most intimate experience that was a surprise to you?");
new AddQuestion("What roles have you seen me play in my life?");
new AddQuestion("What is the funniest moment we've had together?");
new AddQuestion("Describe in your best words the Story of Us?");
new AddQuestion("Do your best impression of me when I'm feeling happy");
new AddQuestion("Do your best impression of me when I'm overwhelmed");
new AddQuestion("When I'm excited, do your best impression of what I look like");
new AddQuestion("When I'm hungry, do your best impression of me when I'm starving");
new AddQuestion("Do an impression of who I was in the beginning of our relationship?");
new AddQuestion("You get most turned on when I____?");
new AddQuestion("Fill in the blank: You and I made it this far because____?");
new AddQuestion("How do you want others to describe us when they see us together?");
new AddQuestion("How has my family relationship changed since we met?");
new AddQuestion("Has my style changed any since we met?");
new AddQuestion("In what ways has your love for me changed in ways that were surprising to you?");
new AddQuestion("How has your physical attraction about me changed over time?");
new AddQuestion("In what way have I changed the most since we first met?");
new AddQuestion("In what ways has being with me changed you?");
new AddQuestion("In what ways have I not changed that you would like to see me change more?");
new AddQuestion("How do you feel our communication has changed since we met?");
new AddQuestion("What things about our relationship have changed the most over time?");
new AddQuestion("How do you think being with me has changed you?");
new AddQuestion("Have I helped you achieve any of the goals you've wanted to?");
new AddQuestion("If I ever got into an accident and lost my memory, what would be the first things you'd tell me about us?");
new AddQuestion("If I had no fear at all, what do you think I'd do first?");
new AddQuestion("If you could go back to any point in our relationship and give yourself some advice, what would it be and at what point?");
new AddQuestion("If you had to pick one memory to define our relationship what would it be? Why?");
new AddQuestion("If you could relive one memory of our relationship forever what would it be?");
new AddQuestion("If you could start our relationship over again, what would you do differently?");
new AddQuestion("If there was a rulebook for our relationship, what would you make the #1 rule (outside of boundaries)?");
new AddQuestion("How do you feel we are still growing togther, in what ways?");
new AddQuestion("What advice would you give me about being your partner, knowing what you know about me now?");
new AddQuestion("What is something I already know but sometimes forget?");
new AddQuestion("What about being with me feels like being home to you?");
new AddQuestion("What am I carrying on my shoulders, that I should let go of?");
new AddQuestion("Is there a question you've been afraid of asking me?");
new AddQuestion("What are you most worried about for my future?");
new AddQuestion("What are 3 favorite memories you have of us together?");
new AddQuestion("When we're together, what kinds of things physically make you feel comfortable?");
new AddQuestion("What in your opinion has changed the most about us?");
new AddQuestion("What kind of things do I do that inspires you the most?");
new AddQuestion("What kind of things do I do that make you feel heard?");
new AddQuestion("What kind of things do I do that makes you feel safe with me?");
new AddQuestion("What things do I do that makes you feel seen and appreciated?");
new AddQuestion("What kind of things do I do the most that makes you feel you can trust me?");
new AddQuestion("What do I do that helps you the most in life?");
new AddQuestion("What kind of things do I do that turns you on?");
new AddQuestion("What do you think I see in you that you don't see in yourself?");
new AddQuestion("What is there about you that you would like me to understand more about you?");
new AddQuestion("In our relationship, what do you cherish the most?");
new AddQuestion("You drive me crazy when____?");
new AddQuestion("I can't believe ____ happened to us?");
new AddQuestion("Sometimes I ____ when you ____?");
new AddQuestion("What about me is the most similar to you, how are we alike?");
new AddQuestion("What about me, makes me the best commitment you've ever made?");
new AddQuestion("How do you feel we are overcoming our fears together?");
new AddQuestion("In what ways can I support you more?");
new AddQuestion("What kinds of things can I do to make life easier for you?");
new AddQuestion("In your own words, how do you feel we can be better together?");
new AddQuestion("In our relationship, how do you feel we can grow further, in what ways?");
new AddQuestion("In our relationship, how do I touch you emotionally?");
new AddQuestion("In what ways do you think we work best together?");
new AddQuestion("In conflict, how do you think we grow as a couple?");
new AddQuestion("In what ways do you feel we love in different ways?");
new AddQuestion("What do you feel is your primary love language?");
new AddQuestion("How would you describe how I've changed since we met?");
new AddQuestion("How do you know when I am really seeing what you're going through?");
new AddQuestion("How do you know when I'm smiling from the heart?");
new AddQuestion("How do you know when I've forgiven you truly?");
new AddQuestion("?");