let questions = [];


function AddQuestion(category, question){
    this.category=category;
    this.question=question;
    questions.push(this)
}

//btn.onclick=()=>{
 //   const randomIndex=Math.floor(Math.random()*activities.length);
   // const choose=activities[randomIndex];
//
  //  activitybox.textContent=choose.name;
    //describebox.textContent=choose.description;
//}



new AddQuestion("?");
new AddQuestion("casual", "What is your favorite childhood memory?")
new AddQuestion("casual", "What is the name of your favorite pet as a child?");
new AddQuestion("casual", "What is your favorite color?");
new AddQuestion("casual", "Where would you like to visit one day?");
new AddQuestion("casual", "What is the coolest video you've seen in a while?");
new AddQuestion("casual", "What is your corniest joke?");
new AddQuestion("casual", "What is your funniest pick up line?");
new AddQuestion("relationship", "What do you find the most attractive about me physically?");
new AddQuestion("relationship","As a person, what do you find the most attractive about me?");
new AddQuestion("casual","What is the coolest thing that happened to you recently?");
new AddQuestion("casual","What is something you're excited about right now?");
new AddQuestion("casual","What do you think is the world's biggest problem?");
new AddQuestion("casual","If money was no problem, what would you do in the next 24 hours?");
new AddQuestion("casual","If you could have just one day with a deceased family member, who would it be?");
new AddQuestion("relationship","What is the happiest memory you have with me?");
new AddQuestion("relationship","What is something that I do that you really like and want to see more of?");
new AddQuestion("relationship","Is there anything I've done in our relationship that you really miss?");
new AddQuestion("relationship","What is something I do that maybe you'd like to see less of?");
new AddQuestion("relationship","How do you feel I could improve as a partner?");
new AddQuestion("relationship","When is the moment you knew I was the one for you?");
new AddQuestion("relationship","If you could right now, kiss or hug?");
new AddQuestion("casual","What tv show made you excited when you were little?");
new AddQuestion("casual","What is something that you're worried about right now?");
new AddQuestion("relationship","What is something that makes you smile when you think of me?");
new AddQuestion("relationship","What is your favorite nickname that I have for you?");
new AddQuestion("relationship","When do you miss me the most?");
new AddQuestion("relationship","What's the first thing you'll do when you see me in person?");
new AddQuestion("casual","If you had any superpower, what would it be?");
new AddQuestion("casual","What is your dreamcar, the one you would have if money was no object?");
new AddQuestion("casual","What is a core memory of us that sticks out to you?");
new AddQuestion("relationship","Is there something I've done in our relationship that really makes you smile?");
new AddQuestion("relationship","Is there something that you would like me to work on about myself?");
new AddQuestion("relationship","Are you nervous about meeting my family one day?");
new AddQuestion("casual","What would you do if you were here right now?");
new AddQuestion("relationship","What is something about me you find really attractive?");
new AddQuestion("relationship","Can you name something about me that you admire?");
new AddQuestion("relationship","What is one of the things I've written that make you smile the most?");
new AddQuestion("casual","How do you feel when you get an unexpected phone call?");
new AddQuestion("relationship","Is there something I do that ever makes you feel anxious?");
new AddQuestion("relationship","Is there something I've done that makes you feel uncomfortable?");
new AddQuestion("relationship","For the most part, do you feel safe with me?");
new AddQuestion("relationship","How do you think your family would react to meeting me for the first time?");
new AddQuestion("casual","How does our taste in music vary from each other?");
new AddQuestion("casual","What is the coolest thing about me?");
new AddQuestion("casual","If you could change anything about yourself what would it be?");
new AddQuestion("relationship","What clothes I wear make you want to see more?");
new AddQuestion("relationship","What kinds of things make you feel less secure in our relationship?");
new AddQuestion("relationship","What can I do to make you feel more secure in our relationship?");
new AddQuestion("relationship","How do you feel when you miss me?");
new AddQuestion("casual","How do you handle awkward situations in conversations?");
new AddQuestion("relationship","What is the most beautiful thing about being with me?");
new AddQuestion("relationship","What do you look forward to the most when we meet in person?");
new AddQuestion("casual","What is something that happened lately that makes you happy?");
new AddQuestion("relationship","When you lay down to rest at night, do you dream of me?");
new AddQuestion("casual","What is the funniest thing about your favorite pet?");
new AddQuestion("casual","What is your favorite planet in the Solar System?");
new AddQuestion("casual","What is your favorite number?");
new AddQuestion("relationship","What is something I used to do that you really miss?");
new AddQuestion("casual","If you could make one change in the world, what would it be?");
new AddQuestion("casual","How do you feel about the way that you look?");
new AddQuestion("casual","If you could change something about yourself physically what would it be?");
new AddQuestion("casual","If you could change something about your life, what would it be?");
new AddQuestion("relationship","What makes you swoon about me?");
new AddQuestion("relationship","What is something about who I am that makes you feel blessed to be with me?");

new AddQuestion("relationship","What do you feel you've sacrificed the most being in this relationship?");
new AddQuestion("relationship","What do you know now that you wish you knew in the beginning of our relationship?");
new AddQuestion("relationship","Is there anything you miss about you and me?");
new AddQuestion("relationship","If I were on my deathbed what do you think my dying wishes would be?");
new AddQuestion("relationship","About our future, what do you think excites me the most?");
new AddQuestion("relationship","In our relationship, what do you think excites me the most?");
new AddQuestion("casual", "The purpose of life is to ____?");
new AddQuestion("relationship","I love you the most when_____?");
new AddQuestion("relationship","I get turned on most when you _____?");
new AddQuestion("relationship","What has been our greatest accomplishment as a couple in your opinion?");
new AddQuestion("relationship","What do you think I'm hesitant to talk to you about?");
new AddQuestion("relationship","What do you think I appreciate the most in life right now?");
new AddQuestion("relationship","When we're apart, what do you think I miss the most about you?");
new AddQuestion("relationship","What do you think I need and are you providing it in your opinion?");
new AddQuestion("relationship","What are some things that you would like to understand more about me?");
new AddQuestion("relationship","In our relationship, what do you think I value the most now?");
new AddQuestion("relationship","If I could hear anything right now, what do you think I'd like to hear the most?");
new AddQuestion("relationship","When do you think I'm most worried for you?");
new AddQuestion("relationship","What part of our relationship do we take for granted and why do you think that is?");
new AddQuestion("relationship","What do you think is our greatest creation together?");
new AddQuestion("relationship","How do you feel our relationship has changed over time?");
new AddQuestion("relationship","How have I changed in our relationship?");
new AddQuestion("relationship","How do you think my habits have changed in our relationship?");
new AddQuestion("relationship","Describe your feelings when you're around me");
new AddQuestion("relationship","Describe our most intimate experience that was a surprise to you?");
new AddQuestion("relationship","What roles have you seen me play in my life?");
new AddQuestion("relationship","What is the funniest moment we've had together?");
new AddQuestion("relationship","Describe in your best words the Story of Us?");
new AddQuestion("relationship","Do your best impression of me when I'm feeling happy");
new AddQuestion("relationship","Do your best impression of me when I'm overwhelmed");
new AddQuestion("relationship","When I'm excited, do your best impression of what I look like");
new AddQuestion("relationship","When I'm hungry, do your best impression of me when I'm starving");
new AddQuestion("relationship","Do an impression of who I was in the beginning of our relationship?");
new AddQuestion("relationship","You get most turned on when I____?");
new AddQuestion("relationship","Fill in the blank: You and I made it this far because____?");
new AddQuestion("relationship","How do you want others to describe us when they see us together?");
new AddQuestion("relationship","How has my family relationship changed since we met?");
new AddQuestion("relationship","Has my style changed any since we met?");
new AddQuestion("relationship","In what ways has your love for me changed in ways that were surprising to you?");
new AddQuestion("relationship","How has your physical attraction about me changed over time?");
new AddQuestion("relationship","In what way have I changed the most since we first met?");
new AddQuestion("relationship","In what ways has being with me changed you?");
new AddQuestion("relationship","In what ways have I not changed that you would like to see me change more?");
new AddQuestion("relationship","How do you feel our communication has changed since we met?");
new AddQuestion("relationship","What things about our relationship have changed the most over time?");
new AddQuestion("relationship","How do you think being with me has changed you?");
new AddQuestion("relationship","Have I helped you achieve any of the goals you've wanted to?");
new AddQuestion("relationship","If I ever got into an accident and lost my memory, what would be the first things you'd tell me about us?");
new AddQuestion("casual","If I had no fear at all, what do you think I'd do first?");
new AddQuestion("relationship","If you could go back to any point in our relationship and give yourself some advice, what would it be and at what point?");
new AddQuestion("relationship","If you had to pick one memory to define our relationship what would it be? Why?");
new AddQuestion("relationship","If you could relive one memory of our relationship forever what would it be?");
new AddQuestion("relationship","If you could start our relationship over again, what would you do differently?");
new AddQuestion("relationship","If there was a rulebook for our relationship, what would you make the #1 rule (outside of boundaries)?");
new AddQuestion("relationship","How do you feel we are still growing togther, in what ways?");
new AddQuestion("relationship","What advice would you give me about being your partner, knowing what you know about me now?");
new AddQuestion("casual", "What is something I already know but sometimes forget?");
new AddQuestion("relationship","What about being with me feels like being home to you?");
new AddQuestion("relationship","What am I carrying on my shoulders, that I should let go of?");
new AddQuestion("relationship","Is there a question you've been afraid of asking me?");
new AddQuestion("relationship","What are you most worried about for my future?");
new AddQuestion("relationship","What are 3 favorite memories you have of us together?");
new AddQuestion("relationship","When we're together, what kinds of things physically make you feel comfortable?");
new AddQuestion("relationship","What in your opinion has changed the most about us?");
new AddQuestion("relationship","What kind of things do I do that inspires you the most?");
new AddQuestion("relationship","What kind of things do I do that make you feel heard?");
new AddQuestion("relationship","What kind of things do I do that makes you feel safe with me?");
new AddQuestion("relationship","What things do I do that makes you feel seen and appreciated?");
new AddQuestion("relationship","What kind of things do I do the most that makes you feel you can trust me?");
new AddQuestion("relationship","What do I do that helps you the most in life?");
new AddQuestion("relationship","What kind of things do I do that turns you on?");
new AddQuestion("relationship","What do you think I see in you that you don't see in yourself?");
new AddQuestion("relationship","What is there about you that you would like me to understand more about you?");
new AddQuestion("relationship","In our relationship, what do you cherish the most?");
new AddQuestion("relationship","You drive me crazy when____?");
new AddQuestion("relationship","I can't believe ____ happened to us?");
new AddQuestion("relationship","Sometimes I ____ when you ____?");
new AddQuestion("relationship","What about me is the most similar to you, how are we alike?");
new AddQuestion("relationship","What about me, makes me the best commitment you've ever made?");
new AddQuestion("relationship","How do you feel we are overcoming our fears together?");
new AddQuestion("relationship","In what ways can I support you more?");
new AddQuestion("relationship","What kinds of things can I do to make life easier for you?");
new AddQuestion("relationship","In your own words, how do you feel we can be better together?");
new AddQuestion("relationship","In our relationship, how do you feel we can grow further, in what ways?");
new AddQuestion("relationship","In our relationship, how do I touch you emotionally?");
new AddQuestion("relationship","In what ways do you think we work best together?");
new AddQuestion("relationship","In conflict, how do you think we grow as a couple?");
new AddQuestion("relationship","In what ways do you feel we love in different ways?");
new AddQuestion("relationship","What do you feel is your primary love language?");
new AddQuestion("relationship","What do you feel is my primary love language?");
new AddQuestion("relationship","How would you describe how I've changed since we met?");
new AddQuestion("relationship","How do you know when I am really seeing what you're going through?");
new AddQuestion("relationship","How do you know when I'm smiling from the heart?");
new AddQuestion("relationship","How do you know when I've forgiven you truly?");
new AddQuestion("relationship","In our relationship, when have you felt that I have left you emotionally and how do you feel about that time now?");
new AddQuestion("relationship","When was the first time you knew I loved you?");
new AddQuestion("relationship","When did I last disappoint you, and how do you feel about it now?");
new AddQuestion("relationship","Describe a time when I made you feel held in our relationship");
new AddQuestion("relationship","When have we been the most successful together?");
new AddQuestion("relationship","When were you most concerned and afraid for me?");
new AddQuestion("relationship","What direction do you think we are headed as a couple?");
new AddQuestion("relationship","Why do you still love me?");
new AddQuestion("relationship","Why do you think I am part of your life?");
new AddQuestion("relationship","Would you rather go first, or be the last one to go, and why?");
new AddQuestion("relationship","What did we have to give up and why?");
new AddQuestion("relationship","Why has being with me been worth it?");
new AddQuestion("relationship","Look me in the eye and tell me something without saying a word");
new AddQuestion("relationship","What do you ____ about me?");
new AddQuestion("relationship","Who inspires us the most at this moment and what makes them resonate so deeply?");
new AddQuestion("relationship","What is something you find funny about me?");
new AddQuestion("relationship","Ask the other player any question you want to");
new AddQuestion("relationship","Tell me something about us as a couple you think I need to hear");
new AddQuestion("relationship","What smell reminds you of me when you come across it?");
new AddQuestion("relationship","What smells like us?");
new AddQuestion("relationship","What moment made you realize choosing me was the right choice?");
new AddQuestion("relationship","Pick 5 words about my future that I can't imagine");
new AddQuestion("relationship","What do you think is keeping me from being the best version of myself?");
new AddQuestion("relationship","What do you think is holding you back and what can I do to help you?");
new AddQuestion("relationship","What do you think is the hardest thing about being my partner?");
new AddQuestion("relationship","What is something in life for you right now that I don't realize?");
new AddQuestion("relationship","What do you think is something I can do to bring me more happiness?");
new AddQuestion("relationship","What do you think makes me different that you didn't realize in the beginning?");
new AddQuestion("relationship","What do you think our current challenges are trying to teach us right now?");
new AddQuestion("relationship","What things in our relationship could be lessons for others?");
new AddQuestion("relationship","What do you think was our biggest challenge in our relationship and what did we learn going through it?");
new AddQuestion("relationship","What do you think is the biggest driver of our relationship?");
new AddQuestion("relationship","What is the most exciting thing to you about our future?");
new AddQuestion("relationship","What excites you the most about our relationship at the moment?");
new AddQuestion("relationship","What habit of mine that I still do drives you a little crazy?");
new AddQuestion("relationship","Has there been anything in our relationship that has disappeared that you miss?");
new AddQuestion("relationship","Is there anything in our relationship that has grown and how do you feel about it now?");
new AddQuestion("relationship","What has healed in you by being with me?");
new AddQuestion("relationship","What have you leaned about intimacy by being with me?");
new AddQuestion("relationship","What have we accomplished together that we could not have done by ourselves?");
new AddQuestion("relationship","What has healed in me, by being with you?");
new AddQuestion("relationship","What lessons of love have you learned by loving me?");
new AddQuestion("relationship","What is something beautiful about our love together?");
new AddQuestion("relationship","What is it in our relationship that keeps us going strong?");
new AddQuestion("relationship","What do you feel is the next chapter in our relationship?");
new AddQuestion("relationship","What makes you love me more?");
new AddQuestion("relationship","What about me makes you melt inside?");
new AddQuestion("relationship","What clothes and colors do I wear that make you swoon for me?");
new AddQuestion("relationship","What mistake do you see me make alot and why do you think I do it?");
new AddQuestion("relationship","What piece of me hasn't changed since we first met?");
new AddQuestion("relationship","What things surprises you about our relationship now?");
new AddQuestion("relationship","What wasn't important in the beginning of our relationship that is important to us now?");
new AddQuestion("relationship","What do you think guides me more my heart or my mind and why?");
new AddQuestion("relationship","What's your favorite part of my body now?");
new AddQuestion("relationship","What's a choice I've made that changed the direction of our relationship?");
new AddQuestion("relationship","What is a decision we made together that changed the course of our relationship?");
new AddQuestion("relationship","What's a habit of mine you have adopted?");
new AddQuestion("relationship","What pain inside of me do you feel that you've helped heal?");
new AddQuestion("relationship","What's a recent thing I've been doing that's been driving you crazy?");
new AddQuestion("relationship","What is something you'd like us to do together this year and why?");
new AddQuestion("relationship","What's an experience you wish we never had together?");
new AddQuestion("relationship","What's one memory we have together that you feel we will never forget?");
new AddQuestion("relationship","What's one moment in your life that if you could go back and change you would and why?");
new AddQuestion("relationship","What's one thing I could do that you feel would improve our relationship?");
new AddQuestion("relationship","Is there something I could do that you would like to see more of?");
new AddQuestion("relationship","Is there an activity that you've been dying to ask me to do for a while?");
new AddQuestion("relationship","What's one thing I could do that if I did would really surprise you?");
new AddQuestion("relationship","What is something I've forgotten about myself and why do you think that is?");
new AddQuestion("relationship","What's one thing you've forgotten about me?");
new AddQuestion("relationship","What song would you have me sing if it could be any song right now?");
new AddQuestion("relationship","What's something we haven't figured out yet and why do you think that is?");
new AddQuestion("relationship","What's something you never want me to forget?");
new AddQuestion("relationship","What's something that you wish I'd give myself?");
new AddQuestion("relationship","What is the greatest gift I've given you?");
new AddQuestion("relationship","What's the greatest gift you've given me?");
new AddQuestion("relationship","What's the hardest thing you've forgiven me for?");
new AddQuestion("relationship","Being with me, what is the most unexpected part?");
new AddQuestion("relationship","What pain inside of me do you wish you could heal?");
new AddQuestion("relationship","What's the wisest thing you've learned from us being together?");
new AddQuestion("relationship","What's the worst advice I've ever given you?");
new AddQuestion("relationship","What's your biggest dream in life right now and how can I help support you more?");
new AddQuestion("relationship","What's you favorite ritual we have together?");
new AddQuestion("relationship","When am I your Hero?");
new AddQuestion("relationship","In our relationship, when did you feel most alone and what did you learn from it?");
new AddQuestion("relationship","When do we argue and how does resolving conflict make us better as a couple?");
new AddQuestion("?");


//let relationship = questions.filter(q=>q.category==="relationship").length;
//This only gives you how many questions have the 'relationship' category
let relationship = questions.filter(q=>q.category==='relationship');
let relationArr= Math.floor(Math.random()*relationship.length);
let random = relationship[relationArr].question;
//makes sense, this doesn't have the .length
let casual = questions.filter(q=>q.category==="casual").length;



//STRUCTURE
//NOTE: This is going to be tied to 3 different functions activated by button click. 
//One function for the 'casual' questions, just the ones for fun and friendly maybe joking
//One function for the 'relationship' questions, the deeper ones my gwapa prinsesa will appreciate
//One function that is to mix all of these. This will be the first function and easiest to write
